server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    bus: #消息总线
      trace:
        enable: true
    config:
      server:
        git:
          uri: https://github.com/hyl1995/spring-cloud.git #配置git仓库地址
          searchPaths: config-file #配置仓库路径
          username: 592443616@qq.com #访问git仓库的用户名
          password: Hyl_For_2018615 #访问git仓库的用户密码
      label: master #配置仓库的分支
  rabbitmq:
    host: localhost
    port: 5672
    username: hyl
    password: 123456
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  endpoints:
    web:
      exposure:
        include: bus-refresh