appKey: "appKey"
appSecret: "appSecret"
bucket: "bucket"
endPoint: "endPoint"

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8

#appKey="appKey"
#appSecret="appSecret"
#bucket="bucket"
#endPoint="endPoint"