server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: core-dev
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411 # 指定了 Zipkin 服务器的地址
zuul:
  routes:
    api:
      path: /api/**
      serviceId: client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/