spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

## 原application.yml配置内容
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8762
#spring:
#  aop:
#    auto: true
#    proxy-target-class: true
#  application:
#    name: client
#  profiles:
#    active: dev, core-dev