server:
  port: 8101
#  maxHttpHeaderSize: 10240000 #防止请求头过大而报错
#  tomcat:
#    maxHttpHeaderSize: 10240000 #防止请求头过大而报错
#    maxHttpPostSize: 10240000
spring:
  application:
    name: config
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hyl1995/spring-cloud.git #配置git仓库地址
          searchPaths: config #配置仓库路径
          username: 592443616@qq.com #访问git仓库的用户名
          password: Hyl_For_2018615 #访问git仓库的用户密码
      label: master #配置仓库的分支
    bus: #启动消息总线及消息跟踪
      trace:
        enabled: true
      enabled: true
#    trace: #开启/httptrace端点
#      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: hyl
    password: 123456
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
## 启动自动刷新配置功能 ##
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh