server:
  port: 8764
spring:
  application:
    name: eurekaclient
  cloud:
    bus: #消息总线
      trace:
        enable: true
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info