server:
  port: 8081
spring:
  application:
    name: feign
  profiles:
    include: dev, core-dev
#开启熔断器
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/