appKey: "appKey"
appSecret: "appSecret"
bucket: "bucket"
endPoint: "endPoint"

rsa:
  publicKey: "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCK09AAGLFp/6ACe+mbM5ZoyAh3Ni7k13w5skwFfoYEhdclXuSiU9pz0MTyanqp00Xfif0xHLqOL4YMh5eN4kg/X1fN7XDb45tHwRGFiTpMuT0Fph1Aw0NJ2NKi8borLdiWBvdFbohreGX9ZdE3miyi5ZBkNusq5l1Sn+ATU4opuwIDAQAB"
  privateKey: "MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAIrT0AAYsWn/oAJ76ZszlmjICHc2LuTXfDmyTAV+hgSF1yVe5KJT2nPQxPJqeqnTRd+J/TEcuo4vhgyHl43iSD9fV83tcNvjm0fBEYWJOky5PQWmHUDDQ0nY0qLxuist2JYG90VuiGt4Zf1l0TeaLKLlkGQ26yrmXVKf4BNTiim7AgMBAAECgYBqm6OUH2JGavXeUnefJmtvhYTyvtoeA9gymlfEtFeIK5t+6DMc8NXFsGE9Y0VVGpgCxH15dH1SaO5AuvNIEqe1WN/gG8RXNOy9YbaqCsKvs7wmy1A2bDEs0BVQzy7uu6gLDoWRzc3z0WCmxLICdS9Z3hUsHXhDb/B8hYE55CQCIQJBAMSUv0THOsRFbdkvOVKN87ef4bKi6TtWrgn5uaD5/Ygrs76Xq7LCUPBBotoSyK13qVj77ZAwCEFxDCmMDhVbHysCQQC0yiSmje6oeqG9qfK4c9JRUY8e//yrb9DXSRmOMyJBRkfoXP6Uxm0P9y7JvK13C/PcJshHqHUS3jP3hwSe1lexAkA8x5znwA28d5cCKqa3jqpHIQjgeZxRO3iuHuc1DXZFLvXxPOXabFgoILMgZ+RiNfhHSgVmqmMzEKfpBKOqGLVnAkEAnpov6QXe92MN/avYScUiH0DjxBhi+6tOlW+FweBODuGvN8RNewtQpo79NvIVY7jSqLJFRcgdXP4erOqAPTBhIQJBAKUTdRMcNXsfeXqztR7LE+/iYUEs3sepiHjFH0Vfo367TYajthZlCqlGFyZXxeJHOCOFslgtnDFegspxVujHG14="
api:
  encrypt:
    key: "d7585fde114abcda"

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8

#appKey="appKey"
#appSecret="appSecret"
#bucket="bucket"
#endPoint="endPoint"